"""Copy baseline caches across the strict-to-leading Yes/No parser fix only.

Original files remain untouched. An audit records old/new signatures; copied
answers were generated by the original implementation, not regenerated.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.jsonl import read_jsonl, write_jsonl
from src.pilot import digest, file_digest, frozen_json, load_manifest, parse_identification, valid_score

OLD_IMPLEMENTATION = "6b2e2eb6c0508722da8c015526528f33bd33e0c5c418544c3ec7ef279810e1a8"
# Filled with the exact reviewed post-fix implementation hash, not any future code.
PARSER_IMPLEMENTATION = "a26b7a6e09d7826bec9de195a58817527e2eb51f0425b782d5bab3c9eae95840"
NEW_IMPLEMENTATION = "2929f57de5bbe915a9cfdea9070cbebcbc6c797abcee297b9f3fc25d0974d652"


def rebind_score(row, old_sig, new_sig, response):
    if (not valid_score(row) or row.get("response_run_hash") != digest(old_sig["response_run"])
            or row.get("judge_run_hash") != digest(old_sig)
            or row.get("response_text_hash") != digest(response["response"])):
        raise ValueError("Score row does not match its original response and judge signature")
    return {**row, "response_run_hash": digest(new_sig["response_run"]),
            "judge_run_hash": digest(new_sig)}


def repair(pilot: Path):
    """Repair only audited rows copied by the original migration; no rejudging."""
    pilot = pilot.resolve()
    audit = json.loads((pilot / "parser_migration.json").read_text())
    if (audit["original_implementation"] not in {OLD_IMPLEMENTATION, PARSER_IMPLEMENTATION}
            or audit["compatible_implementation"] not in {PARSER_IMPLEMENTATION, NEW_IMPLEMENTATION}):
        raise ValueError("Not a supported parser migration")
    if list(pilot.rglob("*.lock")):
        raise ValueError("Stop active workers and inspect locks before repair")
    source = Path(audit["source"])
    entries = {e["path"]: e for e in audit["files"]}
    changes = []
    for relative, entry in entries.items():
        if not (relative.startswith("dev/") and "_judge_" in relative and relative.endswith(".jsonl")):
            continue
        original, target = source / relative, pilot / relative
        if file_digest(original) != entry["original_sha256"]:
            raise ValueError(f"Original score file changed: {original}")
        meta_relative = relative + ".run.json"
        if (file_digest(source / meta_relative) != entries[meta_relative]["original_sha256"]
                or file_digest(pilot / meta_relative) != entries[meta_relative]["copied_sha256"]):
            raise ValueError(f"Judge metadata differs from migration audit: {relative}")
        old_sig = json.loads((source / meta_relative).read_text())
        new_sig = json.loads((pilot / meta_relative).read_text())
        method = new_sig["response_run"]["method"]
        response_path = pilot / "dev" / f"{method}.jsonl"
        generation = json.loads(Path(str(response_path) + ".run.json").read_text())
        if (generation != new_sig["response_run"] or file_digest(response_path) != new_sig["responses_hash"]
                or file_digest(pilot / "split/dev.jsonl") != new_sig["questions_hash"]):
            raise ValueError(f"Current responses differ from judged responses: {relative}")
        responses = {r["id"]: r for r in read_jsonl(response_path)}
        originals = {r["id"]: r for r in read_jsonl(original)}
        rows = list(read_jsonl(target))
        if len({r["id"] for r in rows}) != len(rows):
            raise ValueError(f"Duplicate score rows: {target}")
        replacement, count = [], 0
        for row in rows:
            response = responses[row["response_id"]]
            if response["run_hash"] != digest(generation):
                raise ValueError("Response has invalid generation hash")
            if (row.get("response_run_hash") == digest(generation)
                    and row.get("judge_run_hash") == digest(new_sig)):
                rebind_score(row, new_sig, new_sig, response)  # also validate text and score
                replacement.append(row)
                continue
            if row != originals.get(row["id"]):
                raise ValueError(f"Mismatched row is not an unchanged audited original: {row['id']}")
            replacement.append(rebind_score(row, old_sig, new_sig, response))
            count += 1
        if count:
            changes.append((target, file_digest(target), replacement, count))
    # Validate every affected file before editing any. Backups allow safe reruns after interruption.
    for target, before, rows, count in changes:
        if file_digest(target) != before:
            raise ValueError("Score file changed during repair")
        backup = Path(str(target) + f".before-provenance-fix-{before}.bak")
        if backup.exists():
            if file_digest(backup) != before:
                raise ValueError("Repair backup mismatch")
        else:
            shutil.copy2(target, backup)
        handle, tmp = tempfile.mkstemp(prefix=".score-repair-", dir=target.parent)
        import os
        os.close(handle)
        try:
            write_jsonl(tmp, rows)
            after = file_digest(tmp)
            frozen_json(Path(str(backup) + ".audit.json"), {
                "reason": "repair per-row hashes omitted by parser migration",
                "before_sha256": before, "after_sha256": after, "rows_rebound": count,
                "source_migration": str(pilot / "parser_migration.json"),
            })
            Path(tmp).replace(target)
        finally:
            Path(tmp).unlink(missing_ok=True)
        print(f"[repaired] {target.name}: {count} rows; answers/scores unchanged")
    if not changes:
        print("[repair] No stale migrated row hashes found")


def migrate(source: Path, destination: Path):
    source, destination = source.resolve(), destination.resolve()
    if destination.exists():
        raise ValueError("Destination already exists; use a new PILOT_DIR")
    if source == destination or source in destination.parents:
        raise ValueError("Use a sibling destination, not the source or a child")
    if list(source.rglob("*.lock")):
        raise ValueError("Source has locks; stop its workers and inspect stale locks first")
    current = digest({n: file_digest(REPO_ROOT / "src" / n) for n in
                      ("pilot.py", "pilot_model.py", "steering.py")})
    if current != NEW_IMPLEMENTATION:
        raise ValueError("This migration only supports the reviewed parser-fix implementation")
    manifest = load_manifest(source / "split/manifest.json")
    dev_ids = {q["id"] for q in manifest["questions"] if q["partition"] == "dev"}
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".parser-migration-", dir=destination.parent))
    audit = {"reason": "baseline-compatible parser/alignment fixes; generation prompts and accepted decisions unchanged; fit must be recomputed",
             "source": str(source), "original_implementation": None,
             "compatible_implementation": current, "files": []}
    if (source / "parser_migration.json").exists():
        audit["previous_migration_sha256"] = file_digest(source / "parser_migration.json")

    def track(old, new):
        audit["files"].append({"path": str(old.relative_to(source)),
                               "original_sha256": file_digest(old), "copied_sha256": file_digest(new)})

    try:
        shutil.copytree(source / "split", staging / "split")
        for part in ("fit", "dev", "test"):
            rows = list(read_jsonl(staging / "split" / f"{part}.jsonl"))
            if rows != [q for q in manifest["questions"] if q["partition"] == part]:
                raise ValueError(f"Modified split: {part}")
        for method in ("plain", "fp_identification", "premise_cot"):
            old = source / "dev" / f"{method}.jsonl"
            meta = Path(str(old) + ".run.json")
            if not old.exists() and not meta.exists():
                continue
            spec = json.loads(meta.read_text())
            original_impl = spec["identity"]["implementation_hash"]
            if (original_impl not in {OLD_IMPLEMENTATION, PARSER_IMPLEMENTATION}
                    or spec["method"] != method or spec["partition"] != "dev"
                    or spec["manifest_hash"] != manifest["manifest_hash"]
                    or set(spec["question_ids"]) != dev_ids):
                raise ValueError(f"Unsupported generation signature: {meta}")
            if audit["original_implementation"] not in {None, original_impl}:
                raise ValueError("Mixed source baseline implementations")
            audit["original_implementation"] = original_impl
            new_spec = copy.deepcopy(spec)
            new_spec["identity"]["implementation_hash"] = current
            rows = list(read_jsonl(old)) if old.exists() else []
            seen = set()
            for row in rows:
                if row["id"] not in dev_ids or row["id"] in seen or row["run_hash"] != digest(spec):
                    raise ValueError(f"Invalid cached generation: {old}")
                seen.add(row["id"])
                if method == "fp_identification":
                    previous = re.fullmatch(r"\s*(yes|no)[.!]?\s*", row["review"], re.IGNORECASE)
                    if ((original_impl == OLD_IMPLEMENTATION and not previous)
                            or parse_identification(row["review"]) != row["identified_false_premise"]):
                        raise ValueError("Cached FP decision is not compatible with the parser fix")
                row["run_hash"] = digest(new_spec)
            new = staging / "dev" / old.name
            frozen_json(Path(str(new) + ".run.json"), new_spec)
            track(meta, Path(str(new) + ".run.json"))
            if not old.exists():
                continue
            write_jsonl(new, rows)
            track(old, new)
            for scores in sorted((source / "dev").glob(f"{method}_judge_*.jsonl")):
                score_meta = Path(str(scores) + ".run.json")
                sig = json.loads(score_meta.read_text())
                if (sig["response_run"] != spec or sig["responses_hash"] != file_digest(old)
                        or sig["questions_hash"] != file_digest(source / "split/dev.jsonl")):
                    raise ValueError(f"Invalid judge provenance: {scores}")
                judged = list(read_jsonl(scores))
                if (any(not valid_score(r) or r["response_id"] not in seen for r in judged)
                        or len({r["id"] for r in judged}) != len(judged)):
                    raise ValueError(f"Invalid judge rows: {scores}")
                target = staging / "dev" / scores.name
                old_sig = copy.deepcopy(sig)
                sig["response_run"] = new_spec
                sig["responses_hash"] = file_digest(new)
                by_id = {r["id"]: r for r in rows}
                judged = [rebind_score(r, old_sig, sig, by_id[r["response_id"]]) for r in judged]
                write_jsonl(target, judged)
                frozen_json(Path(str(target) + ".run.json"), sig)
                track(scores, target)
                track(score_meta, Path(str(target) + ".run.json"))
        # Only development baselines are migrated; fit/selection/test results are excluded.
        for entry in audit["files"]:
            if file_digest(source / entry["path"]) != entry["original_sha256"]:
                raise ValueError("Source changed during migration; stop concurrent workers")
        frozen_json(staging / "parser_migration.json", audit)
        staging.rename(destination)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    print(f"[migrated] {destination}; {len(audit['files'])} files audited, original untouched")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path)
    parser.add_argument("--destination", type=Path)
    parser.add_argument("--repair", type=Path, help="Repair an existing audited parser-migration directory")
    args = parser.parse_args()
    if args.repair:
        if args.source or args.destination:
            parser.error("Use --repair alone")
        repair(args.repair)
    elif args.source and args.destination:
        migrate(args.source, args.destination)
    else:
        parser.error("Use --source and --destination, or --repair")
