"""Copy baseline caches across the strict-to-leading Yes/No parser fix only.

Original files remain untouched. An audit records old/new signatures; copied
answers were generated by the original implementation, not regenerated.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.jsonl import read_jsonl, write_jsonl
from src.pilot import digest, file_digest, frozen_json, load_manifest, parse_identification, valid_score

OLD_IMPLEMENTATION = "6b2e2eb6c0508722da8c015526528f33bd33e0c5c418544c3ec7ef279810e1a8"
# Filled with the exact reviewed post-fix implementation hash, not any future code.
NEW_IMPLEMENTATION = "a26b7a6e09d7826bec9de195a58817527e2eb51f0425b782d5bab3c9eae95840"


def migrate(source: Path, destination: Path):
    source, destination = source.resolve(), destination.resolve()
    if destination.exists():
        raise ValueError("Destination already exists; use a new PILOT_DIR")
    if source == destination or source in destination.parents:
        raise ValueError("Use a sibling destination, not the source or a child")
    if list(source.rglob("*.lock")):
        raise ValueError("Source has locks; stop its workers and inspect stale locks first")
    current = digest({n: file_digest(REPO_ROOT / "src" / n) for n in
                      ("pilot.py", "pilot_model.py", "steering.py")})
    if current != NEW_IMPLEMENTATION:
        raise ValueError("This migration only supports the reviewed parser-fix implementation")
    manifest = load_manifest(source / "split/manifest.json")
    dev_ids = {q["id"] for q in manifest["questions"] if q["partition"] == "dev"}
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".parser-migration-", dir=destination.parent))
    audit = {"reason": "leading-verdict parser accepts additional outputs; old valid decisions unchanged",
             "source": str(source), "original_implementation": OLD_IMPLEMENTATION,
             "compatible_implementation": current, "files": []}

    def track(old, new):
        audit["files"].append({"path": str(old.relative_to(source)),
                               "original_sha256": file_digest(old), "copied_sha256": file_digest(new)})

    try:
        shutil.copytree(source / "split", staging / "split")
        for part in ("fit", "dev", "test"):
            rows = list(read_jsonl(staging / "split" / f"{part}.jsonl"))
            if rows != [q for q in manifest["questions"] if q["partition"] == part]:
                raise ValueError(f"Modified split: {part}")
        for method in ("plain", "fp_identification", "premise_cot"):
            old = source / "dev" / f"{method}.jsonl"
            meta = Path(str(old) + ".run.json")
            if not old.exists() and not meta.exists():
                continue
            spec = json.loads(meta.read_text())
            if (spec["identity"]["implementation_hash"] != OLD_IMPLEMENTATION
                    or spec["method"] != method or spec["partition"] != "dev"
                    or spec["manifest_hash"] != manifest["manifest_hash"]
                    or set(spec["question_ids"]) != dev_ids):
                raise ValueError(f"Unsupported generation signature: {meta}")
            new_spec = copy.deepcopy(spec)
            new_spec["identity"]["implementation_hash"] = current
            rows = list(read_jsonl(old)) if old.exists() else []
            seen = set()
            for row in rows:
                if row["id"] not in dev_ids or row["id"] in seen or row["run_hash"] != digest(spec):
                    raise ValueError(f"Invalid cached generation: {old}")
                seen.add(row["id"])
                if method == "fp_identification":
                    previous = re.fullmatch(r"\s*(yes|no)[.!]?\s*", row["review"], re.IGNORECASE)
                    if not previous or parse_identification(row["review"]) != row["identified_false_premise"]:
                        raise ValueError("Cached FP decision is not compatible with the parser fix")
                row["run_hash"] = digest(new_spec)
            new = staging / "dev" / old.name
            frozen_json(Path(str(new) + ".run.json"), new_spec)
            track(meta, Path(str(new) + ".run.json"))
            if not old.exists():
                continue
            write_jsonl(new, rows)
            track(old, new)
            for scores in sorted((source / "dev").glob(f"{method}_judge_*.jsonl")):
                score_meta = Path(str(scores) + ".run.json")
                sig = json.loads(score_meta.read_text())
                if (sig["response_run"] != spec or sig["responses_hash"] != file_digest(old)
                        or sig["questions_hash"] != file_digest(source / "split/dev.jsonl")):
                    raise ValueError(f"Invalid judge provenance: {scores}")
                judged = list(read_jsonl(scores))
                if (any(not valid_score(r) or r["response_id"] not in seen for r in judged)
                        or len({r["id"] for r in judged}) != len(judged)):
                    raise ValueError(f"Invalid judge rows: {scores}")
                target = staging / "dev" / scores.name
                shutil.copy2(scores, target)
                sig["response_run"] = new_spec
                sig["responses_hash"] = file_digest(new)
                frozen_json(Path(str(target) + ".run.json"), sig)
                track(scores, target)
                track(score_meta, Path(str(target) + ".run.json"))
        # Only development baselines are migrated; fit/selection/test results are excluded.
        for entry in audit["files"]:
            if file_digest(source / entry["path"]) != entry["original_sha256"]:
                raise ValueError("Source changed during migration; stop concurrent workers")
        frozen_json(staging / "parser_migration.json", audit)
        staging.rename(destination)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    print(f"[migrated] {destination}; {len(audit['files'])} files audited, original untouched")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--destination", required=True, type=Path)
    args = parser.parse_args()
    migrate(args.source, args.destination)
