"""Twin LoRA (method B, chat 9/18): teach correction on false premises and
ordinary answering on their form-matched true twins, then measure whether the
model corrects held-out FPQ without starting to "correct" NFP/TPQ.

Training rows (origins restricted to the suite's training partitions):
  fpq    the natural FPQ question -> the model's OWN fp_unconditional answer,
         kept only when the Well judge scored it `min_score` (default 5), so the
         target is a correction the judge already accepted (rejection sampling);
  fpara  the Sonnet-rewritten false paraphrase of the same origin -> the same
         target (same myth, same correction);
  twin   the Sonnet-spliced true twin of the same origin -> the model's OWN Plain
         answer to the twin (generated by scripts/lora_twin.py data).
Negatives "none" drops the twins: Well's FPQ-only LoRA as the control.

Evaluation rows: held-out FPQ, every NFP (never trained on, so all 149 are a
transfer measurement), plus the true twins of held-out origins.
"""

from __future__ import annotations

from collections import Counter, defaultdict
import json
from pathlib import Path

from .pilot import digest, normalized

VERSION = "lora-twin-v1"
NEGATIVES = ("twins", "none")


def map_twin_rows(twin_rows, e1_rows, suite_questions):
    """Twins/false paraphrases carry pair_id in the E1 id scheme; map to suite
    IDs by exact normalized question text. Returns (twins, fparas) keyed by
    suite origin id; rows whose origin is not in the suite are dropped."""
    by_text = {normalized(q["question"]): q["id"] for q in suite_questions if q["set"] == "fpq"}
    e1_text = {r["id"]: normalized(r.get("question", "")) for r in e1_rows}
    twins, fparas = {}, {}
    for t in twin_rows:
        origin = by_text.get(e1_text.get(t.get("pair_id"), "")) or (t.get("pair_id") if t.get("pair_id") in by_text.values() else None)
        if origin is None or not isinstance(t.get("question"), str) or not t["question"].strip():
            continue
        if t.get("set") == "tpair":
            twins[origin] = {**t, "origin": origin}
        elif t.get("label_false_premise") == 1:
            fparas[origin] = {**t, "origin": origin}
    return twins, fparas


def judge_scores(well_dir, method):
    """{question id: 0-5 score} for one method from a Well judge directory."""
    from .well_eval import load_plan, read_ledger
    plan, plan_hash = load_plan(well_dir)
    _, scores = read_ledger(well_dir, plan, plan_hash)
    mapping = plan["mapping"].get(method)
    if not mapping:
        raise ValueError(f"Method {method!r} is not in the judge plan at {well_dir}")
    return {qid: scores.get(jobid) for qid, jobid in mapping.items()}


def split_origins(suite_questions, train_partitions):
    train = set(train_partitions)
    if not train <= {"fit", "dev", "test"} or not train:
        raise ValueError("Training partitions must be a nonempty subset of fit/dev/test")
    fpq_train = {q["id"] for q in suite_questions if q["set"] == "fpq" and q["partition"] in train}
    eval_rows = [q for q in suite_questions if q["partition"] not in train]
    if not eval_rows or {q["set"] for q in eval_rows} != {"fpq", "nfp"}:
        raise ValueError("Evaluation partitions must keep both FPQ and NFP")
    return fpq_train, eval_rows


def assemble_training(suite_questions, twins, fparas, fp_answers, fp_scores, twin_answers, *,
                      train_partitions=("fit",), negatives="twins", min_score=5, fpara_positives=True):
    """Build training rows. fp_answers/twin_answers: {id: response text}.
    fp_scores: {fpq id: judge score or None}. Returns (rows, summary)."""
    if negatives not in NEGATIVES:
        raise ValueError(f"negatives must be one of {NEGATIVES}")
    fpq_train, _ = split_origins(suite_questions, train_partitions)
    by_id = {q["id"]: q for q in suite_questions}
    rows, dropped = [], Counter()
    for origin in sorted(fpq_train):
        if negatives == "twins" and origin not in twins:
            dropped["no_twin"] += 1
            continue
        target = fp_answers.get(origin)
        score = fp_scores.get(origin)
        if not isinstance(target, str) or not target.strip():
            dropped["no_fp_answer"] += 1
            continue
        if score is None or score < min_score:
            dropped["fp_answer_below_min_score"] += 1
            continue
        rows.append({"id": origin, "origin": origin, "kind": "fpq", "label": 1,
                     "question": by_id[origin]["question"], "target": target.strip(), "judge_score": score})
        if fpara_positives and origin in fparas:
            f = fparas[origin]
            rows.append({"id": f["id"], "origin": origin, "kind": "fpara", "label": 1,
                         "question": f["question"], "target": target.strip(), "judge_score": score})
        if negatives == "twins":
            t = twins[origin]
            answer = twin_answers.get(t["id"])
            if not isinstance(answer, str) or not answer.strip():
                dropped["twin_without_plain_answer"] += 1
                rows = [r for r in rows if r["origin"] != origin]  # keep pairs complete
                continue
            rows.append({"id": t["id"], "origin": origin, "kind": "twin", "label": 0,
                         "question": t["question"], "target": answer.strip(), "judge_score": None})
    if not rows:
        raise ValueError(f"No training rows; dropped {dict(dropped)}")
    summary = {"version": VERSION, "negatives": negatives, "min_score": min_score,
               "fpara_positives": fpara_positives, "train_partitions": sorted(train_partitions),
               "fpq_train_origins": len(fpq_train), "rows": len(rows),
               "kinds": dict(Counter(r["kind"] for r in rows)),
               "origins_used": len({r["origin"] for r in rows}), "dropped": dict(dropped),
               "data_hash": digest(rows)}
    return rows, summary


def evaluation_rows(suite_questions, twins, train_partitions=("fit",)):
    """Held-out FPQ, EVERY NFP (training never touches NFP, so all 149 are a
    transfer measurement; their original partition is kept for per-partition
    rows), plus the true twins of held-out FPQ origins. Twins are judged with
    the NFP (TPQ) template: their premise is true, so a proper answer neither
    follows nor invents a false claim."""
    _, held = split_origins(suite_questions, train_partitions)
    held_ids = {q["id"] for q in held}
    rows = [{k: q[k] for k in q} for q in held]
    rows += [{k: q[k] for k in q} for q in suite_questions if q["set"] == "nfp" and q["id"] not in held_ids]
    held_fpq = {q["id"] for q in held if q["set"] == "fpq"}
    for origin in sorted(held_fpq):
        if origin in twins:
            t = twins[origin]
            rows.append({"id": t["id"], "question": t["question"], "set": "nfp", "kind": "twin",
                         "origin": origin, "partition": next(q["partition"] for q in held if q["id"] == origin),
                         "group_id": f"twin:{origin}"})
    texts = Counter(normalized(r["question"]) for r in rows)
    dup = [t for t, n in texts.items() if n > 1]
    if dup:
        raise ValueError(f"Duplicate evaluation question text ({len(dup)}); a twin equals its origin?")
    return rows


def row_group(row):
    """Generation is cached per (kind, partition) group so adding a group later
    (e.g. fit-partition NFP) never invalidates a finished group's frozen spec."""
    return f"{row.get('kind') or row['set']}_{row.get('partition', 'na')}"


def encode_example(tokenizer, render, question, target, max_len):
    """Prompt tokens masked (-100); target + end-of-turn supervised. Returns
    (input_ids, labels, truncated)."""
    prompt_ids = tokenizer(render(tokenizer, question), add_special_tokens=False)["input_ids"]
    target_ids = tokenizer(target, add_special_tokens=False)["input_ids"] + [tokenizer.eos_token_id]
    ids = prompt_ids + target_ids
    labels = [-100] * len(prompt_ids) + target_ids
    truncated = len(ids) > max_len
    if truncated:
        if len(prompt_ids) >= max_len:
            raise ValueError(f"Prompt alone exceeds max_len {max_len}")
        ids, labels = ids[:max_len], labels[:max_len]
    return ids, labels, truncated


def pad_batch(items, pad_id):
    """Right-pad a list of (ids, labels) -> dict of python lists."""
    width = max(len(ids) for ids, _ in items)
    input_ids = [ids + [pad_id] * (width - len(ids)) for ids, _ in items]
    attention = [[1] * len(ids) + [0] * (width - len(ids)) for ids, _ in items]
    labels = [lab + [-100] * (width - len(lab)) for _, lab in items]
    return {"input_ids": input_ids, "attention_mask": attention, "labels": labels}


def batches(n, batch_size, seed, epoch):
    import random
    order = list(range(n))
    random.Random(seed * 1000 + epoch).shuffle(order)
    return [order[i:i + batch_size] for i in range(0, n, batch_size)]


def s5_table(questions, score_sets, *, plain_key="plain"):
    """questions: eval rows (id, set, partition, kind?). score_sets: {method: {id: score}}.
    Markdown lines per method x (kind, partition): S5/all, >=4/all (28 §10.1 "clear
    correction" for FPQ), <=2/all (strong over-correction for NFP/twins), mean 1-5,
    and S5 rescue/harm against plain where both are scored. Missing = not counted."""
    groups = defaultdict(list)
    for q in questions:
        kind = q.get("kind") or q["set"]
        groups[(kind, "all")].append(q["id"])
        groups[(kind, q.get("partition", "?"))].append(q["id"])
    lines = ["| Method | Rows | Partition | Valid/expected | S5/all | >=4/all | <=2/all | Mean 1-5 | S5 rescue/harm vs plain |",
             "|---|---|---|---:|---:|---:|---:|---:|---|"]
    out = {}
    plain = score_sets.get(plain_key, {})
    for method, scores in score_sets.items():
        for (kind, part), ids in sorted(groups.items()):
            n = len(ids)
            valid = [scores[i] for i in ids if scores.get(i) is not None]
            readable = [v for v in valid if 1 <= v <= 5]
            s5, ge4, le2 = sum(v == 5 for v in valid), sum(v >= 4 for v in valid), sum(1 <= v <= 2 for v in valid)
            paired = [i for i in ids if scores.get(i) is not None and plain.get(i) is not None]
            rescue = sum(scores[i] == 5 and plain[i] != 5 for i in paired)
            harm = sum(scores[i] != 5 and plain[i] == 5 for i in paired)
            mean = sum(readable) / len(readable) if readable else None
            out[(method, kind, part)] = {"expected": n, "valid": len(valid), "s5": s5, "ge4": ge4, "le2": le2,
                                        "s5_over_all": s5 / n if n else None, "ge4_over_all": ge4 / n if n else None,
                                        "le2_over_all": le2 / n if n else None, "mean": mean,
                                        "rescue": rescue, "harm": harm, "paired": len(paired)}
            pct = lambda k: f"{k}/{n} ({100 * k / n:.1f}%)" if n else "NA"
            lines.append(f"| {method} | {kind} | {part} | {len(valid)}/{n} | {pct(s5)} | {pct(ge4)} | {pct(le2)} | "
                         f"{mean:.2f} | {rescue}/{harm} ({len(paired)}) |" if mean is not None else
                         f"| {method} | {kind} | {part} | {len(valid)}/{n} | {pct(s5)} | {pct(ge4)} | {pct(le2)} | NA | {rescue}/{harm} ({len(paired)}) |")
    return lines, {"|".join(k): v for k, v in out.items()}


def read_answers(path):
    from .jsonl import read_jsonl
    out = {}
    for r in read_jsonl(path):
        if r.get("status", "complete") in {"complete", "completed", "finished"} and isinstance(r.get("response"), str):
            out[r["id"]] = r["response"]
    return out


def write_jsonl(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
